.Dd 25/01/13
.Dt teelogger 1
.Os Darwin
.Sh NAME
.Nm teelogger
.Nd log rotation and tee built into one app
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl b
.Op Fl f Ar file
.Op Fl s Ar size
.Sh DESCRIPTION
.Nm
intercepts standard input, splits the output to standard output, and writes it to log files with automatic log rotation built-in.
.Pp
A list of flags and their descriptions:
.Bl -tag -width -indent
.It Fl h
Print the help message and exit.
.It Fl b
Run in background mode (daemonize).
.It Fl f Ar file
Specify the output file to log to.
.It Fl s Ar size
Specify the maximum log size in bytes before rotating.
.El
